name: rokkhakoboch
description: রক্ষাকবচ — AI-powered Bangla scam detection (mobile)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  mobile_scanner: ^7.0.1
  permission_handler: ^11.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  telephony: ^0.2.0
  image: ^4.5.4
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
