export const MODULES = [
  {
    id: 'sms',
    number: 1,
    title: 'এমএফএস মেসেজ সেন্টিনেল',
    titleEn: 'MFS Message Sentinel',
    description: 'bKash, Nagad, Rocket SMS/মেসেজ বিশ্লেষণ — AI + রুল-বেসড স্ক্যানিং',
    icon: 'sms',
    status: 'active' as const,
    path: '/scan',
  },
  {
    id: 'call_transcript',
    number: 2,
    title: 'কল ট্রান্সক্রিপ্ট বিশ্লেষণ',
    titleEn: 'Call Transcript Analysis',
    description: 'কল রেকর্ডিং বা ট্রান্সক্রিপ্ট আপলোড — লাইভ কল নয়',
    icon: 'call',
    status: 'active' as const,
    path: '/scan?module=call_transcript',
  },
  {
    id: 'url',
    number: 3,
    title: 'URL/ফিশিং লিংক গার্ড',
    titleEn: 'URL Phishing Guard',
    description: 'সন্দেহজন্য লিংকের ডোমেইন ও প্যাটার্ন যাচাই',
    icon: 'link',
    status: 'active' as const,
    path: '/url-check',
  },
  {
    id: 'financial',
    number: 4,
    title: 'আর্থিক প্রতারণা শিল্ড',
    titleEn: 'Financial Fraud Shield',
    description: 'QR পেমেন্ট, ফেক ইনভয়েস, পেমেন্ট গেটওয়ে স্ক্যাম',
    icon: 'payments',
    status: 'roadmap' as const,
    path: '/modules/financial',
  },
  {
    id: 'social',
    number: 5,
    title: 'সোশ্যাল মিডিয়া স্ক্যাম ওয়াচ',
    titleEn: 'Social Media Scam Watch',
    description: 'ফেসবুক/মেসেঞ্জার/টেলিগ্রাম প্রতারণা প্যাটার্ন',
    icon: 'groups',
    status: 'roadmap' as const,
    path: '/modules/social',
  },
  {
    id: 'deepfake',
    number: 6,
    title: 'ডিপফেক/মিডিয়া ভেরিফিকেশন',
    titleEn: 'Deepfake Media Verification',
    description: 'ভুয়া ভিডিও/অডিও সনাক্তকরণ',
    icon: 'videocam',
    status: 'roadmap' as const,
    path: '/modules/deepfake',
  },
  {
    id: 'device',
    number: 7,
    title: 'ডিভাইস সুরক্ষা',
    titleEn: 'Device Protection',
    description: 'ম্যালওয়্যার, স্পাইওয়্যার, অ্যাপ ইন্টিগ্রিটি',
    icon: 'phonelink_lock',
    status: 'roadmap' as const,
    path: '/modules/device',
  },
  {
    id: 'identity',
    number: 8,
    title: 'পরিচয় সুরক্ষা',
    titleEn: 'Identity Protection',
    description: 'NID, SIM-swap, KYC ইম্পারসোনেশন',
    icon: 'badge',
    status: 'roadmap' as const,
    path: '/modules/identity',
  },
  {
    id: 'business',
    number: 9,
    title: 'ব্যবসায়িক সুরক্ষা',
    titleEn: 'Business Protection',
    description: 'SME, এজেন্ট, মার্চেন্ট ফ্রড প্রতিরোধ',
    icon: 'storefront',
    status: 'roadmap' as const,
    path: '/modules/business',
  },
  {
    id: 'threat_intel',
    number: 10,
    title: 'জাতীয় হুমকি বুদ্ধিমত্তা',
    titleEn: 'National Threat Intelligence',
    description: 'সম্প্রদায় রিপোর্ট, প্যাটার্ন ফিড, হুমকি ম্যাপ',
    icon: 'public',
    status: 'partial' as const,
    path: '/feed',
  },
] as const

export type ModuleId = (typeof MODULES)[number]['id']

export const DISCLAIMER =
  'এটি ১০০% নিশ্চিত নয় — এটি একটি ঝুঁকি নির্দেশক টুল'
